#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION $CONTRIB/../electrum/version.py`)
KIIRO_ELECTRUM_VERSION=${VERSION_STRING[2]}
KIIRO_ELECTRUM_VERSION=${KIIRO_ELECTRUM_VERSION#\'}
KIIRO_ELECTRUM_VERSION=${KIIRO_ELECTRUM_VERSION%\'}
export KIIRO_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION $CONTRIB/../electrum/version.py`)
KIIRO_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
KIIRO_ELECTRUM_APK_VERSION=${KIIRO_ELECTRUM_APK_VERSION#\'}
KIIRO_ELECTRUM_APK_VERSION=${KIIRO_ELECTRUM_APK_VERSION%\'}
export KIIRO_ELECTRUM_APK_VERSION

# Check is release
SIMPLIFIED_VERSION_PATTERN="^([^A-Za-z]+).*"
if [[ ${KIIRO_ELECTRUM_VERSION} =~ ${SIMPLIFIED_VERSION_PATTERN} ]]; then
    if [[ ${BASH_REMATCH[1]} == ${KIIRO_ELECTRUM_VERSION} ]]; then
        export IS_RELEASE=y
    fi
fi
